### ISSUE TITLE
[BUG] The `set-output` command is deprecated.

### ISSUE THREAD

**Issue by bdongus** [alirezanet/publish-nuget#7]
This is not really a bug, but neither it is a new feature. But it might become a bug.

Using your tool I get this warning/info:

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Maybe you can update your tool before the set-output command will be disabled.

**Comment by alirezanet** [comment]
Hi @Doxoh,
Sure, I'll check it out this week. 
thank you

**Comment by Kurpanik** [comment]
Looking forward as well, Github will disable it by the end of the month

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023

**Comment by alirezanet** [comment]
Hi, can someone test version `v3.1.0-preview3` please? if you confirm that it's working I'll release `v3.1.0` 

I don't have much time but looks ok to me (tested once and it worked). just want to make sure before releasing it.
thank you

**Comment by Kurpanik** [comment]
Sadly there are no examples for Javascript in the references. Maybe this is an approach? https://github.com/actions/toolkit/issues/1218

**Comment by alirezanet** [comment]
> @alirezanet did this help you? [GerardSmit@47f6a3c](https://github.com/GerardSmit/publish-nuget/commit/47f6a3ca3e127c842e3d7761c6931e902ecd7b29)

This looks a good implementation, 👌
Can you create a PR?

**Comment by alirezanet** [comment]
> @alirezanet done #10

Thank you, I think we can test version `v3.1.0-test1` now. let me know if you did it. if not I'll try to test it till tomorrow

**Comment by alirezanet** [comment]
Fixed in `v3.1.0`. 
thanks to @Doxoh
