### ISSUE TITLE
Update NodeJS to v16

### ISSUE THREAD

**Issue by Kurpanik** [alirezanet/publish-nuget#8]
We should get rid of the action warnings:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: alirezanet/publish-nuget@v3.0.4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by alirezanet** [comment]
Hi @Kurpanik
This week I'll release a new version.
